export const GET_WDATA_REQUEST = "GET_WDATA_REQUEST";
export const GET_WDATA_SUCCESS = "GET_WDATA_SUCCESS";
export const GET_WDATA_FAILURE = "GET_WDATA_FAILURE";
export const GET_MDATA_REQUEST = "GET_MDATA_REQUEST";
export const GET_MDATA_SUCCESS = "GET_MDATA_SUCCESS";
export const GET_MDATA_FAILURE = "GET_MDATA_FAILURE";
